# Generated by Django 5.1.3 on 2024-11-15 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('date_published', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Collaboration'), ('closed', 'Closed for Collaboration'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('category', models.CharField(choices=[('architecture', 'Architecture'), ('industrial_design', 'Industrial Design'), ('graphic_design', 'Graphic Design'), ('urban_promotion', 'Urban Promotion')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
